parameters:
  prism_poll.post_load_listener.class: Prism\PollBundle\Listener\LoadClassMetadataListener

services:
    prism_poll.load_class_metadata:
        class: %prism_poll.post_load_listener.class%
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }
        calls:
            - [ setContainer, [ '@service_container' ] ]
